import "./styles/globals.scss";

export const metadata = {
	title: "Birthdayy | Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="main">{children}</body>
		</html>
	);
}
